import { useCallback, useEffect, useMemo, useState } from "react";
import api from "../../services/axios";
const REPORTS={"most-borrowed":["Livros Mais Emprestados","Ranking dos títulos com maior circulação.","▥"],recommended:["Recomendados","Livros disponíveis para destaque no catálogo.","★"],categories:["Livros por Categoria","Distribuição do acervo por gênero literário.","▤"],"active-users":["Usuários Ativos","Usuários com empréstimos atualmente em andamento.","♙"]};
const CLOSED=["RETURNED","CANCELED","CANCELLED"]; const asList=(data)=>Array.isArray(data)?data:data?.content??[]; const genreLabel=(genre)=>!genre?"Sem categoria":genre.toLowerCase().replaceAll("_"," ").replace(/\b\w/g,(letter)=>letter.toUpperCase());
export default function ReportsPage({type}){
 const [title,description,icon]=REPORTS[type]??REPORTS["most-borrowed"]; const [books,setBooks]=useState([]); const [loans,setLoans]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const loadReportData=useCallback(async()=>{try{setLoading(true);setError("");const requests=[api.get("/books",{params:{page:0,size:100,sort:"title,asc"}})];if(type==="most-borrowed"||type==="active-users")requests.push(api.get("/loans",{params:{page:0,size:100,sort:"requestDate,desc"}}));const [booksRes,loansRes]=await Promise.all(requests);setBooks(asList(booksRes.data));setLoans(asList(loansRes?.data));}catch(err){setError(err.response?.data?.detail||"Erro ao carregar relatório");}finally{setLoading(false);}},[type]);
 // API synchronization is intentionally performed from the effect.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{loadReportData();},[loadReportData]);
 const borrowedRanking=useMemo(()=>{const counts=new Map();loans.forEach((loan)=>{if(loan.bookTitle)counts.set(loan.bookTitle,(counts.get(loan.bookTitle)??0)+1);});return [...counts.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,10);},[loans]);
 const categories=useMemo(()=>{const counts=new Map();books.forEach((book)=>{const label=genreLabel(book.genre);counts.set(label,(counts.get(label)??0)+1);});return [...counts.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));},[books]);
 const recommendations=useMemo(()=>[...books].filter((book)=>Number(book.availableCopies??0)>0).sort((a,b)=>Number(b.loanCount??0)-Number(a.loanCount??0)||a.title.localeCompare(b.title)).slice(0,6),[books]);
 const activeUsers=useMemo(()=>{const counts=new Map();loans.filter((loan)=>!CLOSED.includes(loan.status)).forEach((loan)=>{if(loan.userName)counts.set(loan.userName,(counts.get(loan.userName)??0)+1);});return [...counts.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,10);},[loans]);
 const totalBooks=books.length,totalLoans=loans.length,activeCount=loans.filter((loan)=>!CLOSED.includes(loan.status)).length,genreTotal=categories.reduce((sum,entry)=>sum+entry[1],0),topGenre=categories[0]?.[0]??"—"; const maxBorrowed=borrowedRanking[0]?.[1]??1,maxActive=activeUsers[0]?.[1]??1;
 const donutGradient=useMemo(()=>{if(!genreTotal)return "var(--bg-soft)";const palette=["var(--primary)","var(--secondary)","#94a3b8","#cbd5e1"];let cursor=0;const entries=categories.slice(0,4).map((entry,index)=>{const count=entry[1];const start=cursor;cursor+=count/genreTotal*360;return `${palette[index]} ${start}deg ${cursor}deg`;});return `conic-gradient(${entries.join(",")})`;},[categories,genreTotal]);
 const renderBody=()=>{if(loading)return <div className="empty-state">Carregando relatório...</div>;if(error)return <div className="empty-state"><p className="error-text">{error}</p></div>;if(type==="most-borrowed")return borrowedRanking.length?<div className="report-chart-list">{borrowedRanking.map(([name,count],index)=><div className="report-bar-row" key={name}><div className="report-bar-label"><span>{index+1}. {name}</span><strong>{count}</strong></div><div className="report-bar-track"><span style={{width:`${Math.max(7,count/maxBorrowed*100)}%`}}/></div></div>)}</div>:<div className="empty-state">Nenhum empréstimo registrado.</div>;if(type==="recommended")return recommendations.length?<div className="report-book-grid">{recommendations.map((book)=><article className="report-book-card" key={book.id}>{book.coverUrl?<img src={book.coverUrl} alt={`Capa de ${book.title}`}/>:<div className="book-cover-placeholder">▣</div>}<div><h3>{book.title}</h3><p>{book.authors?.map((author)=>author.name).join(", ")||"Autor não informado"}</p><span>{book.availableCopies} disponível(is)</span></div></article>)}</div>:<div className="empty-state">Nenhum livro disponível para recomendação.</div>;if(type==="categories")return categories.length?<div className="report-category-layout"><div className="report-donut" style={{background:donutGradient}}><div><strong>{genreTotal}</strong><span>livros</span></div></div><div className="report-legend">{categories.map(([category,count],index)=><div key={category}><span className={`legend-dot dot-${index%4}`}/><strong>{category}</strong><span>{count} ({genreTotal?Math.round(count/genreTotal*100):0}%)</span></div>)}</div></div>:<div className="empty-state">Nenhum livro cadastrado.</div>;return activeUsers.length?<div className="report-chart-list">{activeUsers.map(([name,count],index)=><div className="report-bar-row" key={name}><div className="report-bar-label"><span>{index+1}. {name}</span><strong>{count}</strong></div><div className="report-bar-track"><span style={{width:`${Math.max(7,count/maxActive*100)}%`}}/></div></div>)}</div>:<div className="empty-state">Nenhum usuário com empréstimo ativo.</div>;};
 return <div className="page-content reports-page"><div className="page-header"><span className="eyebrow">RELATÓRIOS</span><h1>{title}</h1><p>{description}</p></div><div className="report-kpi-grid"><div className="report-kpi"><span>Livros no acervo</span><strong>{loading?"—":totalBooks}</strong></div><div className="report-kpi"><span>Empréstimos registrados</span><strong>{loading?"—":totalLoans}</strong></div><div className="report-kpi"><span>Empréstimos ativos</span><strong>{loading?"—":activeCount}</strong></div><div className="report-kpi"><span>Gênero líder</span><strong className="report-kpi-text">{loading?"—":topGenre}</strong></div></div><section className="card report-panel"><div className="report-panel-heading"><div className="report-icon" aria-hidden="true">{icon}</div><div><span className="eyebrow">ANÁLISE</span><h2>{title}</h2></div></div>{renderBody()}</section></div>;
}
